### ISSUE TITLE
Umbrella issue for data-plane integrations with OpenSergo Java SDK

### ISSUE THREAD

**Issue by sczyh30** [opensergo/opensergo-java-sdk#5]
This is the umbrella issue for data-plane integrations with OpenSergo Java SDK.

In progress:

- [x] [Sentinel](https://sentinelguard.io/): https://github.com/alibaba/Sentinel/issues/2841
- [x] [Spring Cloud Alibaba](https://github.com/alibaba/spring-cloud-alibaba): https://github.com/alibaba/spring-cloud-alibaba/pull/2921
- [ ] [Apache Dubbo](https://dubbo.apache.org/)

Planning:

- [ ] ShardingSphere
